project:
  type: website
  # resources:
  #   - "images/twitter-card.png"
  #   - "course-materials/_slides/"
    
website:
  open-graph: true
  page-navigation: true
  title: "RAP Markdown"
  description: "RAP Markdown"
  # date: now
  # favicon: _assets/favicon/favicon.ico
  repo-url: https://github.com/craig-shenton/qdown
  repo-actions: [edit, issue]

  twitter-card:
    creator: "@craigrshenton"
    image: "https://pbs.twimg.com/profile_images/800388889114451968/Ta6tqm7s_400x400.jpg"

  page-footer:
    left: "This page is built with ❤️ and [Quarto](https://quarto.org/)."
    # background: "#005eb8"
    right:
    - text: "License"
      href: https://github.com/craig-shenton/qdown/blob/main/LICENSE
    - text: "Code of Conduct"
      href: https://github.com/craig-shenton/qdown/blob/main/CODE_OF_CONDUCT.md

  navbar:
    background: light
    logo: _assets/img/quarto.png
    logo-alt: "Quarto logo."
    title: false
    collapse-below: lg
    left:
      - text: "Introduction"
        href: index.qmd
      - text: "RAP Checklist" 
        file: rap-maturity-framework.qmd
      - text: "Help"
        menu:
          - text: "Report a Bug"
            icon: "bug"
            href: "https://github.com/craig-shenton/qdown/issues"
          - text: "Ask a Question"
            icon: "chat-right-text"
            href: "https://github.com/craig-shenton/qdown/discussions"
          - text: "FAQ"
            icon: "question-circle"
            href: faq/index.qmd
    right:
      - icon: twitter
        href: https://twitter.com/craigrshenton
        aria-label: Twitter
      - icon: github
        href: https://github.com/craig-shenton/qdown
        aria-label: GitHub

  sidebar:
    - id: nav
      style: "floating"
      search: true
      collapse-level: 2
      align: left
      contents:
        - section: "Content"
          contents:
            - text: "Introduction" 
              file: index.qmd
            - text: "RAP Checklist" 
              file: rap-maturity-framework.qmd
      right:
        - icon: github
          href: https://github.com/craig-shenton/qdown
          aria-label: GitHub
format:
  html:
    toc: true
    theme:
      light: [cosmo, _assets/style/theme.scss]
    code-copy: true
    code-overflow: wrap
    css: _assets/style/styles.css
    include-after-body: _assets/style/js.html
    grid:
      sidebar-width: 250px
      body-width: 900px
      margin-width: 300px
    # # Code options
    # code-tools:
    #   source: false
    #   toggle: false
    #   caption: none
    # code-fold: true
    # code-summary: "Show code"
    # code-copy: true
    # code-overflow: wrap
